# Generated by Django 6.0.5 on 2026-05-14 08:04

import articles.models
import ckeditor_uploader.fields
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('subtitle', models.CharField(blank=True, help_text='Appears under the headline', max_length=300)),
                ('excerpt', models.TextField(help_text='Short summary shown in cards & meta description', max_length=500)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('hero_image', models.ImageField(upload_to=articles.models.article_image_path)),
                ('hero_image_caption', models.CharField(blank=True, max_length=300)),
                ('hero_image_credit', models.CharField(blank=True, help_text='Photographer / agency credit', max_length=150)),
                ('video_url', models.URLField(blank=True, help_text='Optional YouTube / Vimeo embed URL')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('featured', 'Featured'), ('breaking', 'Breaking News'), ('editor', "Editor's Pick")], db_index=True, default='normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Auto-publish at this time', null=True)),
                ('seo_title', models.CharField(blank=True, help_text='Overrides title in browser tab & Google', max_length=70)),
                ('seo_description', models.CharField(blank=True, help_text='Overrides excerpt in Google snippet', max_length=160)),
                ('canonical_url', models.URLField(blank=True, help_text='Set if this article was originally published elsewhere')),
                ('og_image', models.ImageField(blank=True, help_text='1200×630px image for social sharing', null=True, upload_to='og/')),
                ('og_title', models.CharField(blank=True, max_length=90)),
                ('og_description', models.CharField(blank=True, max_length=200)),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('reading_time', models.PositiveSmallIntegerField(default=0, editable=False, help_text='Auto-calculated in minutes')),
                ('is_sponsored', models.BooleanField(default=False)),
                ('sponsor_name', models.CharField(blank=True, max_length=100)),
                ('allow_comments', models.BooleanField(default=True)),
                ('show_ads', models.BooleanField(default=True, help_text='Uncheck to suppress AdSense on this article')),
                ('is_premium', models.BooleanField(default=False, help_text='Paywall / subscriber-only content')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='categories.category')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=articles.models.article_image_path)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('credit', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='articles.article')),
            ],
            options={
                'verbose_name': 'Article Image',
                'verbose_name_plural': 'Article Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=130, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=articles.models.author_photo_path)),
                ('title', models.CharField(blank=True, help_text='e.g. Senior Reporter, Editor', max_length=80)),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.author'),
        ),
        migrations.AddField(
            model_name='article',
            name='co_authors',
            field=models.ManyToManyField(blank=True, related_name='co_authored_articles', to='articles.author'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField(max_length=1000)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='articles.comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelatedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_articles', to='articles.article')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.article')),
            ],
            options={
                'verbose_name': 'Related Article',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_at', 'status'], name='articles_ar_publish_c77e57_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'status'], name='articles_ar_categor_961ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['priority', 'status'], name='articles_ar_priorit_f9d4f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='relatedarticle',
            unique_together={('article', 'related')},
        ),
    ]
