# Generated by Django 6.0.5 on 2026-05-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(help_text='Short summary shown in cards and meta description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='hero_image_caption',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='hero_image_credit',
            field=models.CharField(blank=True, help_text='Photographer or agency credit'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Paywall or subscriber only content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_description',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_image',
            field=models.ImageField(blank=True, help_text='1200x630px image for social sharing', null=True, upload_to='og/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_title',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Overrides excerpt in Google snippet'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Overrides title in browser tab and Google'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='sponsor_name',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Appears under the headline'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional YouTube or Vimeo embed URL'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='caption',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='credit',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='title',
            field=models.CharField(blank=True, help_text='e.g. Senior Reporter, Editor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(),
        ),
    ]
