# Generated by Django 6.0.5 on 2026-05-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoredPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser_name', models.CharField(max_length=120)),
                ('advertiser_email', models.EmailField(max_length=254)),
                ('advertiser_logo', models.ImageField(blank=True, null=True, upload_to='sponsors/')),
                ('advertiser_url', models.URLField(blank=True)),
                ('disclosure_text', models.CharField(default='This article is sponsored content.', help_text='Disclosure shown above the article body (required by law)', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount_usd', models.DecimalField(decimal_places=2, help_text='Agreed fee in USD', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sponsored Post',
                'verbose_name_plural': 'Sponsored Posts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AdUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal label e.g. 'Article sidebar 300x250'", max_length=120)),
                ('ad_type', models.CharField(choices=[('adsense', 'Google AdSense'), ('direct_image', 'Direct — Image Banner'), ('direct_html', 'Direct — Custom HTML'), ('house', 'House / Promo Ad')], default='adsense', max_length=20)),
                ('position', models.CharField(choices=[('leaderboard_top', 'Leaderboard — Top of page'), ('leaderboard_bottom', 'Leaderboard — Bottom of page'), ('in_article_1', 'In-Article — After paragraph 3'), ('in_article_2', 'In-Article — After paragraph 6'), ('sidebar_top', 'Sidebar — Top'), ('sidebar_sticky', 'Sidebar — Sticky'), ('between_cards', 'Between article cards'), ('footer', 'Footer banner')], max_length=30)),
                ('size', models.CharField(choices=[('728x90', 'Leaderboard (728×90)'), ('300x250', 'Medium Rectangle (300×250)'), ('336x280', 'Large Rectangle (336×280)'), ('300x600', 'Half Page (300×600)'), ('320x50', 'Mobile Banner (320×50)'), ('resp', 'Responsive (auto-size)')], default='resp', max_length=10)),
                ('adsense_publisher_id', models.CharField(blank=True, help_text='Your ca-pub-XXXXXXXXXXXXXXXX publisher ID', max_length=30)),
                ('adsense_slot_id', models.CharField(blank=True, help_text='The data-ad-slot value from your AdSense account', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('target_url', models.URLField(blank=True, help_text='Where the ad clicks through to')),
                ('custom_html', models.TextField(blank=True, help_text='Paste any third-party ad code here')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for image ads', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('advertiser_name', models.CharField(blank=True, max_length=120)),
                ('advertiser_email', models.EmailField(blank=True, max_length=254)),
                ('campaign_name', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True, help_text='Internal campaign notes')),
                ('impressions', models.PositiveIntegerField(default=0, editable=False)),
                ('clicks', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Restrict this ad to specific categories. Leave blank to show site-wide.', to='categories.category')),
            ],
            options={
                'verbose_name': 'Ad Unit',
                'verbose_name_plural': 'Ad Units',
                'ordering': ['position', 'name'],
            },
        ),
    ]
