# Generated by Django 6.0.5 on 2026-05-14 08:04

import categories.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short blurb shown on the category landing page')),
                ('icon', models.CharField(blank=True, help_text="Tabler icon name, e.g. 'ti-ball-football'", max_length=60)),
                ('color', models.CharField(choices=[('navy', 'Navy'), ('red', 'Red'), ('green', 'Green'), ('gold', 'Gold'), ('purple', 'Purple'), ('teal', 'Teal'), ('orange', 'Orange'), ('pink', 'Pink')], default='navy', max_length=10)),
                ('cover_image', models.ImageField(blank=True, help_text='Banner image shown at top of category page', null=True, upload_to=categories.models.category_image_path)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('show_in_nav', models.BooleanField(default=True, help_text='Show this category in the top navigation bar')),
                ('nav_order', models.PositiveSmallIntegerField(default=0, help_text='Lower number = further left in nav')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Leave blank for top-level categories', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='categories.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['nav_order', 'name'],
            },
        ),
    ]
